version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - micro-net

  user-service:
    image: npdat4/user-service:latest
    container_name: user-service
    ports:
      - "8084:8080"
    depends_on:
      - mongo
    networks:
      - micro-net
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://mongo:27017/userdb
      QUARKUS_MONGODB_DATABASE: userdb

  product-service:
    image: npdat4/product-service:latest
    container_name: product-service
    ports:
      - "8085:8080"
    depends_on:
      - mongo
    networks:
      - micro-net
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://mongo:27017/productdb
      QUARKUS_MONGODB_DATABASE: productdb

  order-service:
    image: npdat4/order-service:latest
    container_name: order-service
    ports:
      - "8086:8080"
    depends_on:
      - mongo
    networks:
      - micro-net
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://mongo:27017/orderdb
      QUARKUS_MONGODB_DATABASE: orderdb

volumes:
  mongo-data:

networks:
  micro-net:
    driver: bridge
